name: CI

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install pnpm and dependencies
        uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
          run_install: true
      - name: Build dist
        run: pnpm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: ${{ secrets.PRODUCTION_DEPLOY_PROD }}
          remote_host: ${{ secrets.STAGING_HOST }}
          remote_port: ${{ secrets.STAGING_PORT }}
          remote_user: ${{ secrets.STAGING_USER }}
          remote_key: ${{ secrets.SFTP_KEY }}
